version: "3.3"
services:
  nginx:
    image: nginx:latest
    volumes:
      - type: "bind"
        source: "./nginx.config"
        target: "/etc/nginx/nginx.conf"
networks:
  default:
    external:
      name: demo
